let weatherIconsMap = {
  "11d": "fa-solid fa-cloud-bolt",
  "11n": "fa-solid fa-cloud-bolt",
  "10d": "fas fa-cloud-sun",
  "10n": "fa-regular fa-cloud-bolt-moon",
  "09d": "fas fa-cloud-moon-rain",
  "09n": "fas fa-cloud-showers-heavy",
  "13d": "fa fa-snowflake-o",
  "13n": "fa fa-snowflake-o",
  "50d": "fas fa-smog",
  "50n": "fas fa-smog",
  "01d": "fas fa-sun",
  "01n": "fas fa-moon",
  "02d": "fas fa-cloud-sun",
  "02n": "fas fa-cloud-moon",
  "03d": "fas fa-cloud-sun",
  "03n": "fas fa-cloud-moon",
  "04d": "fas fa-cloud",
  "04n": "fas fa-cloud"
};
